project:
  type: website
  output-dir: docs

website:
  title: "Exercises for the Big Data lecture"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - get_started.qmd
      - data_sources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



