project:
  type: website
  output-dir: docs

website:
  title: "Exercises for the Big Data lecture"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - get_started.qmd
  #     - data_sources.qmd
  sidebar: 
    style: "floating"
    search: true
    contents: 
      - text: "Get started"
        href: get_started.qmd
      - section: "Data Sources"
        href: data_sources.qmd
        contents: 
          - text: "data shipped with R"
            href: provided_data.qmd
  page-footer: "Copyright 2024, Prof. Dr. Tim Weber" 

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

toc: true

