project:
  type: website
  output-dir: docs

website:
  title: "Exercises for the Big Data lecture"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - get_started.qmd
      - data_sources.qmd
  sidebar: 
    style: "docked"
    search: true
    contents: 
      - text: "Get started"
        href: get_started.qmd
      - text: "Data Sources"
        href: data_sources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



