project:
  type: website
  output-dir: docs
toc: true
website:
  title: "Exercises for the Big Data lecture"
  sidebar: 
    style: "floating"
    search: true
    contents: 
      - text: "Get started"
        href: get_started.qmd
      - section: "Data Sources"
        href: data_sources.qmd
        contents: 
          - text: "data shipped with R"
            href: provided_data.qmd
          - text: "csv files"
            href: csv_files.qmd
          - text: "Calling API's"
            href: API_data.qmd
          - text: "Databases"
            href: databases.qmd
          - text: "Web scraping"
            href: web_scraping.qmd
      - section: "Data Quality"
        href: data_quality.qmd
        contents: 
          - text: "data distributions"
            href: data_distributions.qmd
          - text: "Gage R&R"
            href: gage_rr.qmd
  page-footer: "Copyright 2024, Prof. Dr. Tim Weber" 

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

